### ISSUE TITLE
Login attempts not saving to the audit records table?

### ISSUE THREAD

**Issue by rsyring** [level12/keg-auth#154]
From comparing login attempts between nginx logs and audit table records the pattern of missed audits corresponded to 200 and 400 response codes.

* 200 - Form validation fails: I think this should be audited
* 400 - I don't actually know what is causing this currently.  But it is happening on POST so I'd argue this should be audited too.

**Comment by guruofgentoo** [comment]
Right, the mistake here was wrapping the logging in `on_form_valid`. It really doesn't change the rate-limiting and blocking logic at all to add the additional logging records.

Getting a 400 response on login is strange - I don't see anything obvious that would trigger that in keg-auth itself.

**Comment by guruofgentoo** [comment]
CSRF was the reason for the 400 responses. That one was a bit more tricky to handle, since flask-wtf by default just hijacks the whole view process when CSRF fails, and doesn't really have an override per-view.

Unless, of course, we exempt the view, which requires the auth extension to check if the csrf extension is present, figure out which views need to be exempted, etc. Then, the responders have to call back to the csrf extension to get the error in a place we can trap, make the attempt log, and then re-raise.
